// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { readEnv } from "./src/config.js";

// Evita errores de TypeScript al no estar cargado el entorno de tipos de Node
declare const process: { argv: string[]; env: Record<string, string | undefined> };

// Detecta si se está ejecutando una migración o comando CLI de base de datos
const isMigration = process.argv.some(arg => 
  arg.includes("migrate") || arg.includes("push") || arg.includes("pull") || arg.includes("studio")
);

const databaseUrl = isMigration 
  ? (readEnv("DIRECT_URL") || readEnv("DATABASE_URL"))
  : readEnv("DATABASE_URL");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
